#!/bin/sh
chsh -s $(which bash)
# Clean tmux
rm -f ~/.tmux.conf
# Clean neovim
rm -f ~/.config/nvim
rm -rf ~/.config/nvim/
# Clen fish
rm -f ~/.config/fish
rm -rf ~/.config/fish/
rm -rf ~/.config/omf
rm -rf ~/.local/share/omf

if which yay ; then
    yay -Rs nvm --noconfirm
    yay -Rs fish --noconfirm
    yay -Rs neovim --noconfirm
    yay -Rs tmux --noconfirm
    yay -Rs the_silver_searcher --noconfirm
    yay -Rs pgcli --noconfirm
    yay -Rs python-pip --noconfirm
fi

if which apt-get ; then
    alias pip='pip3'
    # apt-get remove --auto-remove fish
    # apt-get purge fish
    apt-get purge --auto-remove fish
    apt-get purge --auto-remove neovim
    apt-get purge --auto-remove tmux
    apt-get purge --auto-remove silversearcher-ag
    # pgcli
    apt-get purge --auto-remove libpq-dev
    apt-get purge --auto-remove python-dev
    pip uninstall pgcli
    # python
    apt-get purge --auto-remove python-dev python-pip python3-dev python3-pip
fi


