#!/bin/sh

# Exit immediately if a command exits with a non-zero status
set -e

######################
#       Neovim       #
######################

echo "Neovim setup"

# Symlink
ln -sv ~/.dotfiles/neovim/ ~/.config/nvim

# Install Plug - Vim plugin manager
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

######################
#        tmux        #
######################

echo "tmux setup"

# Symlink
ln -s ~/.dotfiles/tmux/.tmux.conf ~/.tmux.conf

