#!/bin/sh

# Exit immediately if a command exits with a non-zero status
set -e

function title {
    echo '################################################################################'
    echo '                         '$1
    echo '################################################################################'
}

title debian

if which apt-get ; then
    apt-get install software-properties-common
    add-apt-repository ppa:neovim-ppa/stable
    apt-add-repository ppa:fish-shell/release-2
    apt-get update
fi

title git

if which git ; then
    # Remove current .gitconfig
    rm -f ~/.gitconfig
    # Symlink
    ln -sv ~/.dotfiles/git/.gitconfig ~/.gitconfig
fi

title python

if ! which pip ; then
    if which yay ; then
        yay -S python-pip --noconfirm
    fi

    if which apt-get ; then
        apt-get install python-dev python-pip python3-dev python3-pip
        alias pip='pip3'
    fi

fi

title the_silver_searcher

if ! which ag ; then
    if which yay ; then
        yay -S the_silver_searcher --noconfirm
    fi

    if which apt-get ; then
        apt-get install silversearcher-ag
    fi
fi

title ripgrep

if ! which ripgrep ; then
    if which yay ; then
        yay -S ripgrep --noconfirm
    fi

    if which apt-get ; then
        apt-get install ripgrep
    fi
fi

title pgcli

if ! which pgcli ; then
    if which yay ; then
        yay -S pgcli --noconfirm
    fi

    if which apt-get ; then
        apt-get install libpq-dev python-dev
        pip install pgcli
    fi
fi

title tmux

if ! which tmux ; then
    # Symlink
    ln -sv ~/.dotfiles/tmux/.tmux.conf ~/.tmux.conf

    # Install tmux
    if which yay ; then
        yay -S tmux --noconfirm
        yay -S xsel --noconfirm
    fi

    if which apt-get ; then
        apt-get install tmux
    fi
fi

title neovim

if ! which nvim ; then
    # Symlink
    ln -sv ~/.dotfiles/neovim/ ~/.config/nvim

    # Install Neovim
    if which yay ; then
        yay -S neovim --noconfirm
        yay -S python-pynvim --noconfirm
        yay -S ttf-inconsolata-go-nerd --noconfirm
        yay -S bat --noconfirm
    fi

    if which apt-get ; then
        apt-get install neovim
    fi

    # Install Plug - Vim plugin manager
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    # Install plugins
    nvim -c SourceInstall
fi

title openvpn

if ! which openvpn ; then
    if which yay ; then
        yay -S openvpn --noconfirm
        yay -S openvpn-update-resolv-conf --noconfirm
    fi
fi

title nvm

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash

title docker

if ! which docker ; then
    if which yay ; then
        yay -S docker --noconfirm
    fi
fi
#curl -sSL https://get.docker.com/ | sh
#usermod -aG docker $USER

title docker-compose

if ! which docker ; then
    if which yay ; then
        yay -S docker-compose --noconfirm
    fi
fi
#curl -L https://github.com/docker/compose/releases/download/1.15.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
#chmod +x ~/docker-compose
#mv ~/docker-compose /usr/local/bin/docker-compose

title fish

if ! which fish ; then

    # Symlink
    ln -sv ~/.dotfiles/fish/ ~/.config/fish
    # Install fish
    if which yay ; then
        yay -S fish --noconfirm
    fi

    if which apt-get ; then
        apt-get install fish
    fi

    # Install Oh My Fish
    curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish
else
    # Install theme and font
    fish -c 'omf install bobthefish'
    fish -c 'omf theme bobthefish'
    # fish -c 'omf install fonts'
    # fish -c 'fonts install --powerline Inconsolata'
    # Install nvm plugin
    fish -c 'omf install nvm'
    # Set fish as default shell
    chsh -s $(which fish)
fi

