#!/bin/sh

# Exit immediately if a command exits with a non-zero status
set -e

function title {
    echo '################################################################################'
    echo '                         '$1
    echo '################################################################################'
}

title debian

if which apt-get ; then
    apt-get install software-properties-common
    add-apt-repository ppa:neovim-ppa/stable
    apt-add-repository ppa:fish-shell/release-2
    apt-get update
fi

title git

if which git ; then
    # Remove current .gitconfig
    rm ~/.gitconfig
    # Symlink
    ln -sv ~/.dotfiles/git/.gitconfig ~/.gitconfig
fi

title python

if ! which pip ; then
    if which yaourt ; then
        yaourt -S python-pip --noconfirm
    fi

    if which apt-get ; then
        apt-get install python-dev python-pip python3-dev python3-pip
        alias pip='pip3'
    fi

fi

title the_silver_searcher

if ! which ag ; then
    if which yaourt ; then
        yaourt -S the_silver_searcher --noconfirm
    fi

    if which apt-get ; then
        apt-get install silversearcher-ag
    fi
fi

title pgcli

if ! which pgcli ; then
    if which yaourt ; then
        yaourt -S pgcli --noconfirm
    fi

    if which apt-get ; then
        apt-get install libpq-dev python-dev
        pip install pgcli
    fi
fi

title neovim

if ! which nvim ; then
    # Symlink
    ln -sv ~/.dotfiles/neovim/ ~/.config/nvim

    # Install Neovim
    pip install neovim
    if which yaourt ; then
        yaourt -S neovim --noconfirm
    fi

    if which apt-get ; then
        apt-get install neovim
    fi

    # Install Plug - Vim plugin manager
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    # Install plugins
    nvim -c SourceInstall
fi

title tmux

if ! which tmux ; then
    # Symlink
    ln -sv ~/.dotfiles/tmux/.tmux.conf ~/.tmux.conf

    # Install tmux
    if which yaourt ; then
        yaourt -S tmux --noconfirm
        yaourt -S xsel --noconfirm
    fi

    if which apt-get ; then
        apt-get install tmux
    fi
fi

title openvpn

if ! which openvpn ; then
    if which yaourt ; then
        yaourt -S openvpn --noconfirm
        yaourt -S openvpn-update-resolv-conf --noconfirm
    fi
fi

title nvm

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash

title docker

curl -sSL https://get.docker.com/ | sh
usermod -aG docker $USER

title docker-compose

curl -L https://github.com/docker/compose/releases/download/1.15.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
chmod +x ~/docker-compose
mv ~/docker-compose /usr/local/bin/docker-compose

title fish

if ! which fish ; then
    # Symlink
    ln -sv ~/.dotfiles/fish/ ~/.config/fish
    # Install fish
    if which yaourt ; then
        yaourt -S fish --noconfirm
    fi

    if which apt-get ; then
        apt-get install fish
    fi

    # Install Oh My Fish
    curl -L https://get.oh-my.fish | fish
else
    # Install theme and font
    fish -c 'omf install shellder'
    fish -c 'omf theme shellder'
    fish -c 'omf install fonts'
    fish -c 'fonts install --powerline Inconsolata'
    # Install nvm plugin
    fish -c 'omf install nvm'
    # Set fish as default shell
    chsh -s $(which fish)
fi

